# Generated by Django 5.2.2 on 2025-07-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_skill_application_user_job_posted_by_job_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Language'), ('other', 'Other')], default='technical', max_length=20),
            preserve_default=False,
        ),
    ]
