# Generated by Django 5.2.2 on 2025-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_aptitudepaper_careertip_mocktestschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
